language: node_js
node_js:
- 12.16.0


cache:
  directories:
    - node_modules

install:
  - npm install
script:
  - npm test
<<<<<<< HEAD

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master
=======
>>>>>>> 7b337a3a9a45b9812a1c7101be0db11939f345cd
